# Generated by Django 4.2.3 on 2024-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('resim', models.FileField(null=True, upload_to='kullanicilar/', verbose_name='Kullanıcı Resmi')),
                ('tel', models.IntegerField(default=0)),
                ('dogum', models.DateField()),
            ],
        ),
    ]
