# Generated by Django 4.2.3 on 2024-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_profiles_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('resim', models.FileField(null=True, upload_to='movieGif/', verbose_name='Film Resmi')),
            ],
        ),
    ]
